version: '3.8'

services:
  tai:
    build:
      context: .
      dockerfile: Dockerfile
    image: tai:latest
    container_name: tai-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 